name: 'Setup Node.js'
description: 'Sets up Node.js for the workflow and caches dependencies'

inputs:
  version:
    description: 'Version of Node.js to use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get version 🧮
      shell: bash
      id: get-version
      run: |
        if [ -f ".nvmrc" ]; then
          NODE_VERSION=$(cat .nvmrc | sed -E 's/^v?//g;t')
        elif [ -z "${{ inputs.version }}" ]; then
          NODE_VERSION=${{ inputs.version }}
        else
          NODE_VERSION=22.x
        fi
        echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.get-version.outputs.version }}

    - name: Cache dependencies 📦
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies 📥
      shell: bash
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: npm ci