name: run unit tests

on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token with access to the npm registry'
        required: true

jobs:
  test:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.token }}
    name: ⚗️ run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ checkout code
        uses: actions/checkout@v4

      - id: setup
        name: 🧱 setup workspace
        uses: nick8green/workflows/actions/node/setup@node-setup

      - name: 🧪 run tests
        shell: bash
        run: |
          case "${{ steps.setup.outputs.package-manager }}" in
            pnpm) pnpm test ;;
            yarn) yarn test ;;
            npm)  npm run test ;;
          esac

      - name: 🗂️ archieve results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 30
