name: run unit tests

on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token with access to the npm registry'
        required: true

jobs:
  deploy:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.token }}
    name: 🏗️ build node package
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ checkout code
        uses: actions/checkout@v4

      - id: setup
        name: 🧱 setup workspace
        uses: nick8green/workflows/actions/node/setup@node-setup

      - name: 🛠️ build package
        shell: bash
        run: |
          case "${{ steps.setup.outputs.package-manager }}" in
            pnpm) pnpm build ;;
            yarn) yarn build ;;
            npm)  npm run build ;;
          esac

      - name: 🗂️ archieve results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: build
          path: dist/
          retention-days: 30
